name: Build All ReVanced Applications

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Setup Java
      uses: actions/setup-java@v3.3.0
      with:
        distribution: "zulu"
        java-version: "17"
        java-package: jdk

    - name: Download YouTube Music arm64-v8a
      run: |
        cd yt.music.64.v8a
        chmod +x download.sh
        ./download.sh

    - name: Compile YouTube Music arm64-v8a
      run: |
        cd yt.music.64.v8a
        chmod +x compile.sh
        ./compile.sh experimental

    - name: Sign YouTube Music arm64-v8a
      run: |
        chmod +x youtube/sign.sh
        ./youtube/sign.sh

    - name: Download YouTube Music arm-v7a
      run: |
        cd yt.music.v7a
        chmod +x download.sh
        ./download.sh

    - name: Compile YouTube Music arm-v7a
      run: |
        cd yt.music.v7a
        chmod +x compile.sh
        ./compile.sh experimental

    - name: Sign YouTube Music arm-v7a
      run: |
        chmod +x youtube/sign.sh
        ./youtube/sign.sh

    - name: Download TikTok
      run: |
        cd tiktok
        python download.py

    - name: Compile TikTok
      run: |
        cd tiktok
        chmod +x compile.sh
        ./compile.sh

    - name: Sign TikTok
      run: |
        chmod +x youtube/sign.sh
        ./youtube/sign.sh

    - name: Download Reddit
      run: |
        cd reddit
        python download.py

    - name: Compile Reddit
      run: |
        cd reddit
        chmod +x compile.sh
        ./compile.sh

    - name: Sign Reddit
      run: |
        chmod +x youtube/sign.sh
        ./youtube/sign.sh

    - name: Download Twitter
      run: |
        cd twitter
        python download.py

    - name: Compile Twitter
      run: |
        cd twitter
        chmod +x compile.sh
        ./compile.sh

    - name: Sign Twitter
      run: |
        chmod +x youtube/sign.sh
        ./youtube/sign.sh

    - name: Download YouTube
      run: |
        cd youtube
        chmod +x download.sh
        ./download.sh

    - name: Compile YouTube
      run: |
        cd youtube
        chmod +x compile.sh
        ./compile.sh experimental

    - name: Sign YouTube
      run: |
        chmod +x youtube/sign.sh
        ./youtube/sign.sh

    - name: Upload packages
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "stable"
        draft: true
        title: "${{ env.date_now }} - ReVanced Latest"
        files: |
          youtube/micro.g.apk
          youtube/output/release/*.apk
          twitter/output/release/*.apk
          reddit/output/release/*.apk
          tiktok/output/release/*.apk
          yt.music.v7a/output/release/*.apk
          yt.music.64.v8a/output/release/*.apk
