name: Build All ReVanced Applications

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Setup Java
      uses: actions/setup-java@v3.3.0
      with:
        distribution: "zulu"
        java-version: "17"
        java-package: jdk

    - name: Download Reddit
      run: |
        cd reddit
        python reddit_download.py

    - name: Compile Reddit
      run: |
        cd reddit
        chmod +x compile_reddit.sh
        ./compile_reddit.sh
        echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Sign Reddit
      run: |
        chmod +x youtube/sign_packages.sh
        ./youtube/sign_packages.sh

    - name: Download Twitter
      run: |
        cd twitter
        python twitter_download.py

    - name: Compile Twitter
      run: |
        cd twitter
        chmod +x compile_twitter.sh
        ./compile_twitter.sh
        echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Sign Twitter
      run: |
        chmod +x youtube/sign_packages.sh
        ./youtube/sign_packages.sh

    - name: Download YouTube
      run: |
        cd youtube
        chmod +x youtube_download.sh
        ./youtube_download.sh

    - name: Compile YouTube
      run: |
        cd youtube
        chmod +x compile_youtube.sh
        ./compile_youtube.sh
        echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Sign YouTube
      run: |
        chmod +x youtube/sign_packages.sh
        ./youtube/sign_packages.sh
        
    - name: Download YouTube Music v7a
      run: |
        cd youtube/music/v7a
        chmod +x download_music.sh
        ./download_music.sh
        
    - name: Compile YouTube Music v7a
      run: |
        cd youtube/music/v7a
        chmod +x compile.sh
        ./compile.sh
        echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Sign YouTube Music v7a
      run: |
        chmod +x youtube/sign_packages.sh
        ./youtube/sign_packages.sh

    - name: Download YouTube Music 64-v8a
      run: |
        cd youtube/music/64-v8a
        chmod +x download_music.sh
        ./download_music.sh
        
    - name: Compile YouTube Music 64-v8a
      run: |
        cd youtube/music/64-v8a
        chmod +x compile.sh
        ./compile.sh
        echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Sign YouTube Music 64-v8a
      run: |
        chmod +x youtube/sign_packages.sh
        ./youtube/sign_packages.sh
        
    - name: Download TikTok
      run: |
        cd tiktok
        chmod +x tiktok_download.sh
        ./tiktok_download.sh
        
    - name: Compile TikTok
      run: |
        cd tiktok
        chmod +x compile_tiktok.sh
        ./compile_tiktok.sh
        echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Sign TikTok
      run: |
        chmod +x youtube/sign_packages.sh
        ./youtube/sign_packages.sh
        
    - name: Upload packages
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.date_now }}"
        draft: true
        title: "${{ env.date_now }} - ReVanced Latest"
        files: |
          youtube/vanced-microg.apk
          youtube/output/release/*.apk
          youtube/music/v7a/output/release/*.apk
          youtube/music/64-v8a/output/release/*.apk
          reddit/output/release/*.apk
          twitter/output/release/*.apk
          tiktok/output/release/*.apk
