name: Build WarnWetter

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Setup Java
      uses: actions/setup-java@v3.3.0
      with:
        distribution: "zulu"
        java-version: "17"
        java-package: jdk

    - name: Download base packages
      run: |
        cd warnwetter
        python ww_download.py

    - name: Compile ReReddit
      run: |
        cd warnwetter
        chmod +x ww_compile.sh
        ./ww_compile.sh
        echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Sign packages
      run: |
        chmod +x revanced/sign_packages.sh
        ./revanced/sign_packages.sh

    - name: Upload packages
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.date_now }}"
        draft: true
        title: "${{ env.date_now }} - ReVanced WarnWetter"
        files: |
          warnwetter/output/release/*.apk
