name: Build Revanced YouTube

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Setup Java
      uses: actions/setup-java@v3.3.0
      with:
        distribution: "zulu"
        java-version: "17"
        java-package: jdk

    - name: Download base packages
      run: |
        cd revanced
        chmod +x youtube_download.sh
        ./youtube_download.sh

    - name: Compile ReVanced
      run: |
        cd revanced
        chmod +x compile_revanced.sh
        ./compile_revanced.sh
        echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Sign packages
      run: |
        chmod +x revanced/sign_packages.sh
        ./revanced/sign_packages.sh

    - name: Upload packages
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        draft: true
        title: "r${{ env.date_now }}"
        files: |
          revanced/vanced-microg.apk
          revanced/output/release/*.apk
