name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Setup Java
      uses: actions/setup-java@v3.3.0
      with:
        distribution: "zulu"
        java-version: "17"
        java-package: jdk

    - name: Download YouTube Music arm64-v8a
      run: |
        cd yt-music-64-v8a
        chmod +x download.sh
        ./download.sh

    - name: Compile YouTube Music arm64-v8a
      run: |
        cd revanced
        chmod +x compile.sh
        ./compile.sh experimental
        echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Sign YouTube Music arm64-v8a
      run: |
        chmod +x youtube/sign.sh
        ./youtube/sign.sh

    - name: Upload packages
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        draft: true
        title: "Test"
        files: |
          yt-music-64-v8a/*.apk
